### ISSUE TITLE
Support  IOTX-ERC20 and IOTX

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-tube#3]
The faucet now supports IOTXT (ERC20 token on Ethereum Kovan). We need to add support of:
-- IOTX-ERC20 on Ethereum mainnet
-- IOTX native coin on IoTeX mainnet

Configuration needs to be separated too.

**Comment by guo** [comment]
native token on testnet. right?

**Comment by raullenchai** [comment]
> native token on testnet. right?
Yes. Three type of tokens.

**Comment by raullenchai** [comment]
Done in https://github.com/iotexproject/iotex-tube/pull/5
